# Generated by Django 3.0.4 on 2020-03-26 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('opinion_id', models.IntegerField()),
                ('author', models.CharField(max_length=255)),
                ('recomendation', models.BooleanField()),
                ('stars', models.IntegerField()),
                ('confirmed_by_purchase', models.BooleanField()),
                ('issue_data', models.DateField()),
                ('purchase_date', models.DateField()),
                ('usefull', models.IntegerField()),
                ('useless', models.IntegerField()),
                ('content', models.CharField(max_length=500)),
                ('cons', models.CharField(max_length=255)),
                ('pros', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
