# Generated by Django 3.0.4 on 2020-03-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200326_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opinion',
            name='issue_data',
        ),
        migrations.AddField(
            model_name='opinion',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='opinion',
            name='cons',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='pros',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
