# Generated by Django 3.0.4 on 2020-03-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_opinion_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cons',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='mean_stars',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='opinions',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='pros',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
