# Generated by Django 3.0.4 on 2020-03-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='recomendation',
            field=models.CharField(default='POLECAM', max_length=255),
            preserve_default=False,
        ),
    ]
